### ISSUE TITLE
undefined method `build_where` in Rails 5.0.0.beta2

### ISSUE THREAD

**Issue by robotvert** [DockYard/postgres_ext#180]
Hi,

The current master doesn't work with Rails 5.0.0.beta2.

Given a `Project` model containing a `category_ids` integer array, here's what happens when using `any` (edited for brevity):

```
Project.where.any(category_ids: 1).count

NoMethodError:   Project Load (40.9ms)  SELECT "projects".* FROM "projects"
undefined method `build_where' for #<Project::ActiveRecord_Relation:0x007fd6dd05bd40>
Did you mean?  build_with
  from (...)/activerecord-5.0.0.beta2/lib/active_record/relation/delegation.rb:123:in `method_missing'
  from (...)/activerecord-5.0.0.beta2/lib/active_record/relation/delegation.rb:93:in `method_missing'
  from (...)/postgres_ext/lib/postgres_ext/active_record/relation/query_methods.rb:86:in `build_where_chain'
  from (...)/postgres_ext/lib/postgres_ext/active_record/relation/query_methods.rb:104:in `equality_to_function'
  from (...)/postgres_ext/lib/postgres_ext/active_record/relation/query_methods.rb:41:in `any'
```

Not related to this issue but FYI using Ruby 2.3.0 it outputs warnings:

```
alias_method_chain is deprecated. Please, use Module#prepend instead. 
From module, you can access the original method using super.
```
from [this line in relation/query_methods.rb](https://github.com/DockYard/postgres_ext/blob/master/lib/postgres_ext/active_record/relation/query_methods.rb#L250)

**Comment by daniel-rikowski** [comment]
It looks like some of the private members of `ActiveRecord::Relation` have changed. For example the `build_where` method is gone and instead `where_clause_factory` is used. Also `where_values` has been renamed to `where_clause`.

But perhaps fixing [`build_where_chain`](https://github.com/DockYard/postgres_ext/blob/master/lib/postgres_ext/active_record/relation/query_methods.rb#L85) is enough to restore Rails 5 compatibility.

Something like this: (not tested)
```ruby
def build_where_chain(opts, rest, &block)
  if @scope.respond_to?(:where_clause_factory) # Rails 5
    where_clause = @scope.send(:where_clause_factory).build(opts, rest)
    @scope.references!(PredicateBuilder.references(opts)) if Hash === opts
    @scope.where_clause += where_clause
  else # Rails 4
    where_value = @scope.send(:build_where, opts, rest).map(&block)
    @scope.references!(PredicateBuilder.references(opts)) if Hash === opts
    @scope.where_values += where_value
  end
  @scope
end
```

**Comment by edpaget** [comment]
Thanks will look into this soon.

**Comment by daniel-rikowski** [comment]
It looks like there are other issues with Rails 5, too.  For example in `arel.rb` there is a hardcoded dependency on Rails 4: 
`gdep = Gem::Dependency.new('activerecord', '~> 4.2.0')`

**Comment by andrew** [comment]
Just ran into this with rails 5.0.0.rc1 as well, https://github.com/simpl1g/postgres_ext/commit/a8d60a9f5a278d5e9a9eaaf8833b6dc61320368f has a partial fix but it doesn't solve the `undefined method 'build_where'` issue

**Comment by shaneog** [comment]
Any update on this?

**Comment by edpaget** [comment]
Sorry, I am now longer writing Rails applications, and haven't looked at Rails 5. I will look at pull requests for changes to support it, and would also be open to handing this library over to someone else. 

But I don't think I have time to work on Rails 5 support.

**Comment by shaneog** [comment]
@edpaget I will do some work on Rails 5 support, and open a PR. 
Would you prefer that the same gem version will support Rails 4.x and Rails 5.x at the same time?

**Comment by edpaget** [comment]
Thanks a log @shaneog. I'd prefer the gem to continue supporting multiple versions of Rails. We test for the ActiveRecord version [here](https://github.com/DockYard/postgres_ext/blob/master/lib/postgres_ext/arel.rb), and load the Arel monkey patches that way. 

If that doesn't work I'm fine to say Version 3 supports Rails 4.1 and 4.2 and Version 4 supports Rails 5.

**Comment by shaneog** [comment]
I'll see what I can do. There's significant differences in Arel 7 and AR 5 so I don't want to litter the code with `if` statements. Let me take a closer look and confirm.

**Comment by shmay** [comment]
If anyone just wants to use CTEs in Rails 5, I ripped out the code for that and put it in a separate gem: https://github.com/shmay/ctes_in_my_pg
